# Generated by Django 5.0.6 on 2024-06-25 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('question', models.CharField(choices=[('TEXT', 'TEXT'), ('NUMBER', 'NUMBER'), ('MULTIPLE_CHOICES', 'MULTIPLE_CHOICES'), ('SINGLE_CHOICE', 'SINGLE_CHOICE')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='detailssection',
            name='listing',
        ),
        migrations.AddField(
            model_name='detailssection',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('RENT', 'Rent')], max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('unit_number', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='properties/videos')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'SELLER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iamge', models.ImageField(upload_to='properties/iamges')),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property')),
            ],
        ),
        migrations.AddField(
            model_name='detailssection',
            name='property_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.property'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qustion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=200)),
                ('multiple', models.BooleanField(default=False)),
                ('qustion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qustion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.question')),
                ('choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.questionchoice')),
            ],
        ),
        migrations.CreateModel(
            name='StepSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.detailssection')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='details_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.stepsection'),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
