# Generated by Django 5.0.6 on 2024-06-27 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_question_remove_detailssection_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_price', models.IntegerField()),
                ('meeting_date', models.DateTimeField()),
                ('canceled_at', models.DateField()),
                ('meeting_type', models.CharField(choices=[('IN_PERSON', 'IN_PERSON'), ('VIRTUAL', 'VIRTUAL')], max_length=200)),
                ('reply_type', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], max_length=200)),
                ('replied_at', models.DateField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
