# Generated by Django 5.0.6 on 2024-06-28 19:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_propertytype_property_property_type'),
        ('showings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='Showing',
        ),
    ]
